# Generated by Django 5.0.6 on 2024-06-27 22:15
from django.contrib.auth.hashers import make_password
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    def insertData(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        Permission = apps.get_model('auth', 'Permission')
        User = apps.get_model('auth', 'User')
        UserProfile = apps.get_model('access', 'UserProfile')

        access_manager_group = Group(name='Administrador de Accesos')
        access_manager_group.save()

        station_manager_group = Group(name='Administrador de Surtidor')
        station_manager_group.save()

        refinery_manager_group = Group(name='Administrador de Refinería')
        refinery_manager_group.save()

        salesperson_group = Group(name='Vendedor')
        salesperson_group.save()

        driver_group = Group(name='Conductor')
        driver_group.save()

        add_user = Permission.objects.get(codename='add_user')
        change_user = Permission.objects.get(codename='change_user')
        delete_user = Permission.objects.get(codename='delete_user')
        view_user = Permission.objects.get(codename='view_user')
        add_station = Permission.objects.get(codename='add_station')
        change_station = Permission.objects.get(codename='change_station')
        delete_station = Permission.objects.get(codename='delete_station')
        view_station = Permission.objects.get(codename='view_station')

        access_manager_permissions = [
            add_user,
            change_user,
            delete_user,
            view_user,
            add_station,
            change_station,
            delete_station,
            view_station,
        ]
        access_manager_group.permissions.set(access_manager_permissions)

        admin_user = User(
            username='admin@admin.com',
            password=make_password('admin'),
            email='admin@admin.com',
            first_name='Admin',
            last_name='User',
            is_superuser=True,
            is_staff=True,
        )
        admin_user.save()
        user_profile = UserProfile(user=admin_user, phone='1234567890')
        user_profile.role = access_manager_group
        user_profile.save()

    operations = [
        migrations.RunPython(insertData),
    ]
