# Generated by Django 5.0.6 on 2024-07-09 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=100)),
                ('model', models.FloatField()),
                ('capacity', models.FloatField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fuel_quantity', models.FloatField()),
                ('fuel_price', models.FloatField()),
                ('date', models.DateField()),
                ('completed', models.BooleanField()),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refinery.fueltype')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refinery.truck')),
            ],
        ),
        migrations.CreateModel(
            name='RechargeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_quantity', models.FloatField()),
                ('station_id', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refinery.fueltype')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refinery.route')),
            ],
        ),
    ]
