# Generated by Django 5.0.6 on 2024-06-27 22:15
from django.contrib.auth.hashers import make_password
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refinery', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    def insertData(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        Permission = apps.get_model('auth', 'Permission')

        access_manager_group = Group(name='Administrador de Accesos')
        access_manager_group.save()

        station_manager_group = Group(name='Administrador de Surtidor')
        station_manager_group.save()

        refinery_manager_group = Group(name='Administrador de Refinería')
        refinery_manager_group.save()

        salesperson_group = Group(name='Vendedor')
        salesperson_group.save()

        driver_group = Group(name='Conductor')
        driver_group.save()

        add_truck = Permission.objects.get(codename='add_truck')
        change_truck = Permission.objects.get(codename='change_truck')
        delete_truck = Permission.objects.get(codename='delete_truck')
        view_truck = Permission.objects.get(codename='view_truck')

        add_route = Permission.objects.get(codename='add_route')
        change_route = Permission.objects.get(codename='change_route')
        delete_route = Permission.objects.get(codename='delete_route')
        view_route = Permission.objects.get(codename='view_route')

        add_fueltype = Permission.objects.get(codename='add_fueltype')
        change_fueltype = Permission.objects.get(codename='change_fueltype')
        delete_fueltype = Permission.objects.get(codename='delete_fueltype')
        view_fueltype = Permission.objects.get(codename='view_fueltype')

        add_rechargerequest = Permission.objects.get(codename='add_rechargerequest')
        change_rechargerequest = Permission.objects.get(codename='change_rechargerequest')
        delete_rechargerequest = Permission.objects.get(codename='delete_rechargerequest')
        view_rechargerequest = Permission.objects.get(codename='view_rechargerequest')

        refinery_manager_permissions = [
            add_truck, change_truck, delete_truck, view_truck,
            add_route, change_route, delete_route, view_route,
            add_fueltype, change_fueltype, delete_fueltype, view_fueltype,
            add_rechargerequest, change_rechargerequest, delete_rechargerequest, view_rechargerequest,
        ]

        driver_permissions = [
            view_route,
            view_rechargerequest, change_rechargerequest,
            view_truck,
        ]

        refinery_manager_group.permissions.set(refinery_manager_permissions)
        driver_group.permissions.set(driver_permissions)

    operations = [
        migrations.RunPython(insertData),
    ]
