# Generated by Django 5.0.6 on 2024-07-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinery', '0003_init_fuel_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
