# Generated by Django 5.0.6 on 2024-07-08 05:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('fuel_types', models.ManyToManyField(to='sales.fueltype')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(max_length=100)),
                ('nit', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client')),
                ('fuel_quantity', models.FloatField()),
                ('total', models.FloatField()),
                ('fuel_price', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.fueltype')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.pump')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fuel_types', models.ManyToManyField(to='sales.fueltype')),
            ],
        ),
        migrations.AddField(
            model_name='pump',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.station'),
        ),
        migrations.CreateModel(
            name='FuelStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.fueltype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.station')),
            ],
        ),
    ]
