# Generated by Django 5.0.6 on 2024-07-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_init_roles'),
    ]

    def insertData(apps, schema_editor):
        FuelType = apps.get_model('sales', 'FuelType')
        fuel_types = [
            FuelType(name='Gasolina Especial'),
            FuelType(name='Gasolina Premium'),
            FuelType(name='Diésel'),
            FuelType(name='Gas Natural Vehicular'),
            FuelType(name='Gas Licuado de Petróleo'),
        ]
        FuelType.objects.bulk_create(fuel_types)

    operations = [
        migrations.RunPython(insertData),
    ]
